// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadRunqueueRaw returns the embedded CollectionSpec for RunqueueRaw.
func LoadRunqueueRaw() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_RunqueueRawBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load RunqueueRaw: %w", err)
	}

	return spec, err
}

// LoadRunqueueRawObjects loads RunqueueRaw and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*RunqueueRawObjects
//	*RunqueueRawPrograms
//	*RunqueueRawMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadRunqueueRawObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadRunqueueRaw()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// RunqueueRawSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type RunqueueRawSpecs struct {
	RunqueueRawProgramSpecs
	RunqueueRawMapSpecs
}

// RunqueueRawSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type RunqueueRawProgramSpecs struct {
	HandleSwitchRaw *ebpf.ProgramSpec `ebpf:"handle_switch_raw"`
	HandleWakeupRaw *ebpf.ProgramSpec `ebpf:"handle_wakeup_raw"`
}

// RunqueueRawMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type RunqueueRawMapSpecs struct {
	Events   *ebpf.MapSpec `ebpf:"events"`
	WakeupTs *ebpf.MapSpec `ebpf:"wakeup_ts"`
}

// RunqueueRawObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadRunqueueRawObjects or ebpf.CollectionSpec.LoadAndAssign.
type RunqueueRawObjects struct {
	RunqueueRawPrograms
	RunqueueRawMaps
}

func (o *RunqueueRawObjects) Close() error {
	return _RunqueueRawClose(
		&o.RunqueueRawPrograms,
		&o.RunqueueRawMaps,
	)
}

// RunqueueRawMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadRunqueueRawObjects or ebpf.CollectionSpec.LoadAndAssign.
type RunqueueRawMaps struct {
	Events   *ebpf.Map `ebpf:"events"`
	WakeupTs *ebpf.Map `ebpf:"wakeup_ts"`
}

func (m *RunqueueRawMaps) Close() error {
	return _RunqueueRawClose(
		m.Events,
		m.WakeupTs,
	)
}

// RunqueueRawPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadRunqueueRawObjects or ebpf.CollectionSpec.LoadAndAssign.
type RunqueueRawPrograms struct {
	HandleSwitchRaw *ebpf.Program `ebpf:"handle_switch_raw"`
	HandleWakeupRaw *ebpf.Program `ebpf:"handle_wakeup_raw"`
}

func (p *RunqueueRawPrograms) Close() error {
	return _RunqueueRawClose(
		p.HandleSwitchRaw,
		p.HandleWakeupRaw,
	)
}

func _RunqueueRawClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed runqueueraw_bpfel.o
var _RunqueueRawBytes []byte
