// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadRunqueue returns the embedded CollectionSpec for Runqueue.
func LoadRunqueue() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_RunqueueBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Runqueue: %w", err)
	}

	return spec, err
}

// LoadRunqueueObjects loads Runqueue and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*RunqueueObjects
//	*RunqueuePrograms
//	*RunqueueMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadRunqueueObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadRunqueue()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// RunqueueSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type RunqueueSpecs struct {
	RunqueueProgramSpecs
	RunqueueMapSpecs
}

// RunqueueSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type RunqueueProgramSpecs struct {
	HandleSwitch *ebpf.ProgramSpec `ebpf:"handle_switch"`
	HandleWakeup *ebpf.ProgramSpec `ebpf:"handle_wakeup"`
}

// RunqueueMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type RunqueueMapSpecs struct {
	Events   *ebpf.MapSpec `ebpf:"events"`
	WakeupTs *ebpf.MapSpec `ebpf:"wakeup_ts"`
}

// RunqueueObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadRunqueueObjects or ebpf.CollectionSpec.LoadAndAssign.
type RunqueueObjects struct {
	RunqueuePrograms
	RunqueueMaps
}

func (o *RunqueueObjects) Close() error {
	return _RunqueueClose(
		&o.RunqueuePrograms,
		&o.RunqueueMaps,
	)
}

// RunqueueMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadRunqueueObjects or ebpf.CollectionSpec.LoadAndAssign.
type RunqueueMaps struct {
	Events   *ebpf.Map `ebpf:"events"`
	WakeupTs *ebpf.Map `ebpf:"wakeup_ts"`
}

func (m *RunqueueMaps) Close() error {
	return _RunqueueClose(
		m.Events,
		m.WakeupTs,
	)
}

// RunqueuePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadRunqueueObjects or ebpf.CollectionSpec.LoadAndAssign.
type RunqueuePrograms struct {
	HandleSwitch *ebpf.Program `ebpf:"handle_switch"`
	HandleWakeup *ebpf.Program `ebpf:"handle_wakeup"`
}

func (p *RunqueuePrograms) Close() error {
	return _RunqueueClose(
		p.HandleSwitch,
		p.HandleWakeup,
	)
}

func _RunqueueClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed runqueue_bpfel.o
var _RunqueueBytes []byte
