apiVersion: v1
kind: Service
metadata:
  name: collector-ebpf
  namespace: ebpf
  labels:
    app: collector-ebpf
spec:
  selector:
    app: collector-ebpf
  ports:
  - name: metrics
    port: 2112
    targetPort: metrics
